### ISSUE TITLE
SSH connexion lost after server reboot

### ISSUE THREAD

**Issue by s-duret** [centreon/centreon-connectors#2] opened 2015-09-10 08:56 UTC
Hello,

I use SSH Connector. After a reboot of remote server, I lost connexion.
I have to restart centengine to resolve this.
Centengine have to retry connexion when he lost it.

Regards,

**Comment by ganoze** [comment] 2015-09-10 09:01
Duplicate of #1

**Closed by ganoze** 2015-09-10 09:01 UTC
Labels: bug, duplicate

**Comment by s-duret** [comment] 2015-09-10 09:31
Sorry, I didn't see that
